### PR TITLE
fix: Extra quotes and spaces

### PR DESCRIPTION
**Pull request by binyu1231**
Signed-off-by: binyu1231 <binyu1231@gmail.com>

### Steps

Description

I tried to use the plugin in Slidev. rendering result can't pass syntax checking.

fix: input element renders 2 quotes at the end.
chore: space count will be more reasonable.
chore: change quotes from double to single when they are in JS.

### Related Issue(s)

NaN

### CODE REVIEW

**Comment by mrdrogdrog** [comment]
Usually we use prettier in our repositories for the code quality like quotes and all. Seems like we missed that here. Anyway. It has been added in the meantime. Please update your PR branch.

**Comment by DerMolly** [comment]
Hey @binyu1231,

your branch seems to be in conflict with the main branch currently.

**Comment by mrdrogdrog** [comment]
@DerMolly only if we rebase. My plan is to squash it as soon as I had the time to review it.

**Review by mrdrogdrog — APPROVED** [review]

**Comment by mrdrogdrog** [comment]
Looks good :) I'll publish it later

**Comment by mrdrogdrog** [comment]
@binyu1231 Your fix has been included in release https://github.com/hedgedoc/markdown-it-better-task-lists/releases/tag/v1.0.4

**Pull request merged**
